### PR TITLE
Add auth tests

### LINKED ISSUE #65: Authentication tests
assign to me

### PR DESCRIPTION
**Pull request by Devkalion**
close #65 
Run with command: 
`python3 manage.py test`

### CODE REVIEW

**Comment by esikachev** [comment]
Please, add this test to our CI to .travis.yml

**Comment by Devkalion** [comment]
@esikachev complite

**Comment by esikachev** [comment]
one more comment. can you create the second job for it? 1 job - flake8, 2 - unit tests

**Comment by esikachev** [comment]
@Devkalion this is the stage, not a job :)

**Comment by esikachev** [comment]
I mean like this https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs

**Comment by Devkalion** [comment]
like this?

**Comment by esikachev** [comment]
yep, not ideal, but we can leave like this. Otherwise, better to use the SWITCH variable like TEST_SUITE=flake8 or TEST_SUITE=unittests. It will be more human-readable. And in the "script" section use IF-ELSE block for switching the commands for running

**Comment by Devkalion** [comment]
can you give some example of this?

**Comment by esikachev** [comment]
`# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "3.6"
# List the versions of Django you'd like to test against
env:
  - TEST_SUITE=flake8
  - TEST_SUITE=unittests
# Tell it the things it will need to install when it boots
install: 
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# Tell Travis how to run the test script itself
script:
  - if [[ "$TEST_SUITE" == "flake8" ]]; then flake8 --count *.py; fi
  - if [[ "$TEST_SUITE" == "unittests" ]]; then cd bookshelf; python manage.py test; fi`

**Comment by Devkalion** [comment]
Travis was updated

**Pull request merged**
